#
# This file contains configuration flags to customize your site
#

#gems
gems: ['jekyll-github-metadata']

# theme
theme: jekyll-theme-cayman

# repository
repository: ricovitch/ricovitch.github.io

# Name of your site (displayed in the header)
title: Eric Hélier

# Short bio or description (displayed in the header)
description: Frontend Developer from Toulouse

# indicate whether to provide a download URL
show_downloads: false

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-274964-1

# jekyll excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - cacert.pem
  - rundev.sh
  - update.sh
  - README.md
